In [5]:
import numpy as np
import csv
class matrix:
    
    #creating a instance attribute for importing "Data.csv"
    def __init__(self, file):
        self.file = file
        
    def load_from_csv(self, file):
        #opening the csv file
        csvfile = open(self.file)
        read = csv.reader(csvfile)
        rows = []
        arr = []
        #importing all the element in array_2d
        for row in read:
            rows.append(row)
        for i in range(len(rows)):
            for j in range(len(rows[0])):
                a = rows[i][j]
                arr.append(float(a))
        self.array_2d = (np.array(arr)).reshape(178,13)
        return self.array_2d
    
    def standerdise(self):
        self.load_from_csv(self.file)
        arr2 = []
        for i in range(len(self.array_2d[0])):
            for j in range(len(self.array_2d)):
                Dij = self.array_2d[j][i]
                mean_D = self.array_2d[:,i].mean()
                max_D = max(self.array_2d[:,i])
                min_D = min(self.array_2d[:,i])
                D_stand = (Dij - mean_D)/(max_D-min_D)
                arr2.append(D_stand)
        k = np.array(arr2)
        #Reshaping and transposing the array_2d matrix and transpose
        self.array_2d = k.reshape(13,178).T
        
    def get_distance(self, K, weights, beta):
        S = np.zeros((178,1))
        w = get_initial_weights(13)
        ai = m.array_2d
        bi = get_centroids(m.array_2d, S, K)
        arr2 = []
        
        for i in range(178):
            arr = []
            for c in range(K):
                d = 0
                for j in range(13):
                    #Here the Euclidian distance between array_2d and centroids
                    d = d + (w[j]**beta)*(ai[i][j]-bi[c][j])**2
                arr.append(d)
            k = np.array(arr)
            min_dis = k.argmin()
            arr2.append(min_dis)
            S[i].fill(arr2[i])
        #returning the S matrix
        return np.array(S)
    
def get_count_frequency(S):
    # find and count unique values
    (unique, counts) = np.unique(S,return_counts=True)
    frequencies = np.asarray((unique, counts))
    return frequencies.T
    
    
def get_initial_weights(m):
    arr = []
    k = np.random.rand(m)
    for i in k:
        a = i/sum(k)
        arr.append(a)
    weights = np.array(arr)
    return weights



def get_centroids(array_2d, S, K):
    centroids = np.empty((178,13))
    #taking a random value from 0 to 178
    ee = np.random.randint(178)
    #taking the step position
    cc = ee+K
    #copy K different values for centroids
    copy = m.array_2d[ee:cc]
    centroids = centroids[:K] + copy
    return centroids

    
def get_groups(m, K, beta):
    m = matrix('Data.csv')
    m.standerdise()
    data = m.array_2d
    S = np.zeros((178,1))
    cen = get_centroids(m.array_2d, S, K)
    weights = get_initial_weights(13)
    return m.get_distance(K, weights, beta)
    

def get_new_weights(array_2d, centroids, S):
    for i in range(178):
        ai = m.array_2d
        bi = get_centroids(m.array_2d, S, K)
        arr = []
        d = 0
        for j in range(13):
            delta = (ai[i][j]-bi[c][j])**2
        arr.append(d)
        return arr
    
    
m = matrix('Data.csv')
m.standerdise()


def run_test():
    m = matrix('Data.csv')
    for k in range(2,5):
        for beta in range(11,25):
            S = get_groups(m,k,beta/10)
            print(str(k)+'-'+str(beta)+'='+str(get_count_frequency(S)))

In [6]:
run_test()

2-11=[[  0. 121.]
 [  1.  57.]]
2-12=[[  0. 177.]
 [  1.   1.]]
2-13=[[  0. 128.]
 [  1.  50.]]
2-14=[[ 0. 95.]
 [ 1. 83.]]
2-15=[[  0.   8.]
 [  1. 170.]]
2-16=[[  0. 136.]
 [  1.  42.]]
2-17=[[  0. 152.]
 [  1.  26.]]
2-18=[[  0. 136.]
 [  1.  42.]]
2-19=[[  0.  26.]
 [  1. 152.]]
2-20=[[ 0. 96.]
 [ 1. 82.]]
2-21=[[  0. 134.]
 [  1.  44.]]
2-22=[[  0.  78.]
 [  1. 100.]]
2-23=[[  0.  78.]
 [  1. 100.]]
2-24=[[  0.  29.]
 [  1. 149.]]
3-11=[[ 0. 24.]
 [ 1. 80.]
 [ 2. 74.]]
3-12=[[  0.  48.]
 [  1.  26.]
 [  2. 104.]]
3-13=[[  0.  15.]
 [  1. 147.]
 [  2.  16.]]
3-14=[[ 0. 56.]
 [ 1. 42.]
 [ 2. 80.]]
3-15=[[  0.  24.]
 [  1. 122.]
 [  2.  32.]]
3-16=[[ 0. 59.]
 [ 1. 54.]
 [ 2. 65.]]
3-17=[[  0.  13.]
 [  1.  60.]
 [  2. 105.]]
3-18=[[  0.  36.]
 [  1. 103.]
 [  2.  39.]]
3-19=[[ 0. 71.]
 [ 1. 32.]
 [ 2. 75.]]
3-20=[[ 0. 54.]
 [ 1. 58.]
 [ 2. 66.]]
3-21=[[ 0. 85.]
 [ 1. 55.]
 [ 2. 38.]]
3-22=[[  0.  28.]
 [  1.  20.]
 [  2. 130.]]
3-23=[[  0.  37.]
 [  1. 116.]
 [  2.  25.]]
3-24=[[  0.

In [15]:
m = matrix('Data.csv')

In [16]:
m.standerdise()

In [23]:
S = get_groups(m, 4, .2)

In [24]:
get_count_frequency(S)

array([[ 0., 74.],
       [ 1., 10.],
       [ 2., 63.],
       [ 3., 31.]])

TypeError: get_count_frequency() takes 1 positional argument but 2 were given

In [7]:
weights = get_initial_weights(13)

def get_distance(K, weights, beta):
    S = np.zeros((178,1))
    w = get_initial_weights(13)
    ai = m.array_2d
    bi = get_centroids(m.array_2d, S, K)
    arr2 = []

    for i in range(178):
        arr = []
        for c in range(K):
            d = 0
            for j in range(13):
                d = d + (w[j]**beta)*(ai[i][j]-bi[c][j])**2
            arr.append(d)
        k = np.array(arr)
        min_dis = k.argmin()
        arr2.append(min_dis)
        S[i].fill(arr2[i])
    print(S)

In [8]:
get_distance(3, weights, .2)

[[0.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [2.]
 [0.]
 [0.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [0.]
 [2.]
 [0.]
 [2.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.]
 [0.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.

In [63]:
import numpy as np
import csv
csvfile = open("Data.csv")
read = csv.reader(csvfile)
rows = []
for row in read:
    rows.append(row)

arr = []
    
for i in range(len(rows)):
    for j in range(len(rows[0])):
        a = rows[i][j]
        arr.append(float(a))
abc = np.array(arr).reshape(178,13)

In [2]:
kk = []
for i in range(len(abc[0])):
    for j in range(len(abc)):
        a = abc[j][i]
        a_stand = (a - abc[:,i].mean())/(max(abc[:,i])-min(abc[:,i]))
        kk.append(a_stand)
k = np.array(kk)

In [3]:
c = k.reshape(13,178).T

In [4]:
c

array([[ 0.32352158, -0.12378425,  0.03394821, ...,  0.06711428,
         0.47923612,  0.22689497],
       [ 0.05246895, -0.10995026, -0.12113201, ...,  0.07524436,
         0.28875993,  0.21619596],
       [ 0.04194264,  0.00467425,  0.16229045, ...,  0.0589842 ,
         0.20451084,  0.31248698],
       ...,
       [ 0.07089001,  0.38412089, -0.05696088, ..., -0.29873938,
        -0.38523274,  0.06284361],
       [ 0.04457422,  0.05012879,  0.00186264, ..., -0.2906093 ,
        -0.36325472,  0.06640994],
       [ 0.2972058 ,  0.34854776,  0.19972361, ..., -0.28247922,
        -0.37058073, -0.13330475]])

In [5]:
m = matrix('Data.csv')

NameError: name 'matrix' is not defined

In [6]:
m.standerdise()

NameError: name 'm' is not defined

In [156]:
def get_initial_weights(m):
    arr = []
    k = np.random.rand(m)
    for i in k:
        a = i/sum(k)
        arr.append(a)
    weights = np.array(arr)
    return weights


In [157]:
get_initial_weights(5)

array([0.16232222, 0.27835307, 0.02721186, 0.2362019 , 0.29591094])

In [158]:
def get_centroid(array_2d, S, K):
    centroids = np.empty((178,13))
    S = np.zeros((178,1))
    np.random.shuffle(array_2d)
    copy = array_2d[:K]
    centroids = centroids[:K] + copy
    print(centroids)

In [132]:
centroids = np.empty((178,13))
S = np.zeros((178,1))
ee = np.random.randint(178)
cc = ee+3
copy = m.array_2d[ee:cc]
centroids = centroids[:3] + copy
print(centroids)

[[ 7.73211118e-003 -2.83863303e-001 -3.51078532e-001 -1.80151743e-001
  -1.49364924e-001 -1.19004262e-001  1.54079552e-004 -2.29913080e-001
  -4.12930209e-002  7.19010354e+140  8.48378526e+136  4.10113498e+223
  -2.53133565e-001]
 [ 9.11160086e+130  1.09417329e-001 -7.30036652e-002  7.19010354e+140
   8.48378526e+136  4.10113498e+223 -1.49634950e-001  9.11160086e+130
  -2.02176302e-001 -2.05468420e-001  7.19010354e+140  8.48378526e+136
   4.10113498e+223]
 [-1.76478415e-001  9.11160086e+130 -2.22736286e-001 -2.42007413e-001
   7.19010354e+140  8.48378526e+136  4.10113498e+223 -2.23659105e-002
   9.11160086e+130 -1.41475246e-001  8.33744405e-002  7.19010354e+140
   8.48378526e+136]]


In [133]:
ee = np.random.randint(10)
cc = ee+3

In [134]:
ee

8

In [135]:
cc

11

In [136]:
get_centroid(m.array_2d, S, 2)

NameError: name 'get_centroid' is not defined

In [137]:
w = get_initial_weights(13)

In [138]:
w

array([0.03572229, 0.11555091, 0.11920847, 0.05982032, 0.0643693 ,
       0.14962806, 0.10975517, 0.07738742, 0.06935338, 0.10281695,
       0.01254225, 0.00220563, 0.08163983])

In [139]:
ai = m.array_2d

In [140]:
ai[0][0]

0.32352158486102883

In [141]:
bi = centroids

In [142]:
bi[0][0]

0.007732111176818103

In [145]:
arr2 =[]
S = np.zeros((178,1))
for i in range(178):
    arr = []
    for c in range(3):
        d = 0
        for j in range(13):
            d = d + (w[j]**.2)*(ai[i][j]-bi[c][j])**2
        arr.append(d)
    k = np.array(arr)
    
    min_dis = k.argmin()
    print(min_dis)
    arr2.append(min_dis)
    S[i].fill(min_dis)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


<ipython-input-145-2621e7d99939>:8: RuntimeWarning: overflow encountered in double_scalars
  d = d + (w[j]**.2)*(ai[i][j]-bi[c][j])**2


In [176]:
S

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [177]:
S

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [326]:
m.array_2d

array([[-0.08700473, -0.26805303, -0.06765607, ...,  0.22158582,
         0.20084784, -0.21176409],
       [ 0.00773211, -0.2838633 , -0.35107853, ...,  0.1890655 ,
        -0.04823641, -0.25313357],
       [-0.24226789, -0.18702536,  0.07138136, ..., -0.02231662,
         0.21183685, -0.25812643],
       ...,
       [ 0.07878474, -0.12180797, -0.12113201, ...,  0.05085412,
         0.0579907 ,  0.38381365],
       [ 0.01299527, -0.05659058,  0.4564081 , ...,  0.14028501,
         0.21549986,  0.05927728],
       [ 0.04194264,  0.00467425,  0.16229045, ...,  0.0589842 ,
         0.20451084,  0.31248698]])

In [168]:
tt = np.zeros((5,1))

In [169]:
tt

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [170]:
tt[0].fill(5)

In [171]:
tt

array([[5.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [40]:
ar = np.array([[1],[1],[2],[5],[3],[6],[5],[9],[3],[2],[5],[6],[1]])

In [42]:
ar

array([[1, 1, 2, 5, 3, 6, 5, 9, 3, 2, 5, 6, 1]])

In [41]:
np.unique(ar)

array([1, 2, 3, 5, 6, 9])

In [38]:
(unique, counts) = np.unique(ar,return_counts=True)
frequencies = np.asarray((unique, counts)).T

In [39]:
print(frequencies)

[[1 3]
 [2 2]
 [3 2]
 [5 3]
 [6 2]
 [9 1]]
