In [21]:
import numpy as np
import csv
class matrix:
    
    def __init__(self, file):
        self.file = file
        
    def load_from_csv(self, file):
        csvfile = open(self.file)
        read = csv.reader(csvfile)
        rows = []
        arr = []
        for row in read:
            rows.append(row)
        for i in range(len(rows)):
            for j in range(len(rows[0])):
                a = rows[i][j]
                arr.append(float(a))
        self.array_2d = (np.array(arr)).reshape(178,13)
        return self.array_2d
        #print(self.array_2d)
    
    def standerdise(self):
        self.load_from_csv(self.file)
        arr2 = []
        for i in range(len(self.array_2d[0])):
            for j in range(len(self.array_2d)):
                Dij = self.array_2d[j][i]
                mean_D = self.array_2d[:,i].mean()
                max_D = max(self.array_2d[:,i])
                min_D = min(self.array_2d[:,i])
                D_stand = (Dij - mean_D)/(max_D-min_D)
                arr2.append(D_stand)
        k = np.array(arr2)
        self.array_2d = k.reshape(13,178).T
        return self.array_2d
        
    def get_distance(self, other_matrix, weights, beta):
        
        pass
        
    
    def get_count_frequency():
        pass
    
    
def get_initial_weights(m):
    arr = []
    k = np.random.rand(m)
    for i in k:
        a = i/sum(k)
        arr.append(a)
    weights = np.array(arr)
    return weights

def get_cetroids(array_2d):
    pass

In [22]:
m = matrix("Data.csv")

In [23]:
m.standerdise()

array([[ 0.32352158, -0.12378425,  0.03394821, ...,  0.06711428,
         0.47923612,  0.22689497],
       [ 0.05246895, -0.10995026, -0.12113201, ...,  0.07524436,
         0.28875993,  0.21619596],
       [ 0.04194264,  0.00467425,  0.16229045, ...,  0.0589842 ,
         0.20451084,  0.31248698],
       ...,
       [ 0.07089001,  0.38412089, -0.05696088, ..., -0.29873938,
        -0.38523274,  0.06284361],
       [ 0.04457422,  0.05012879,  0.00186264, ..., -0.2906093 ,
        -0.36325472,  0.06640994],
       [ 0.2972058 ,  0.34854776,  0.19972361, ..., -0.28247922,
        -0.37058073, -0.13330475]])

In [24]:
get_initial_weights(7)

array([0.00137997, 0.02217159, 0.26495586, 0.12771441, 0.03085934,
       0.26561535, 0.28730348])

In [25]:
m.array_2d

array([[ 0.32352158, -0.12378425,  0.03394821, ...,  0.06711428,
         0.47923612,  0.22689497],
       [ 0.05246895, -0.10995026, -0.12113201, ...,  0.07524436,
         0.28875993,  0.21619596],
       [ 0.04194264,  0.00467425,  0.16229045, ...,  0.0589842 ,
         0.20451084,  0.31248698],
       ...,
       [ 0.07089001,  0.38412089, -0.05696088, ..., -0.29873938,
        -0.38523274,  0.06284361],
       [ 0.04457422,  0.05012879,  0.00186264, ..., -0.2906093 ,
        -0.36325472,  0.06640994],
       [ 0.2972058 ,  0.34854776,  0.19972361, ..., -0.28247922,
        -0.37058073, -0.13330475]])